-- Script para crear las bases de datos, esquemas y datos iniciales

-- Crear la base de datos cliente_db
CREATE DATABASE cliente_db;
\c cliente_db

-- Crear la tabla persona (para Cliente y Persona)
CREATE TABLE persona (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         dtype VARCHAR(31) NOT NULL,
                         direccion VARCHAR(255),
                         edad INTEGER NOT NULL,
                         genero VARCHAR(255),
                         identificacion VARCHAR(255) NOT NULL,
                         nombre VARCHAR(255) NOT NULL,
                         telefono VARCHAR(255),
                         cliente_id VARCHAR(255),
                         contrasena VARCHAR(255),
                         estado BOOLEAN,
                         CONSTRAINT UKr5vsms84ih2viwd6tatk9o5pq UNIQUE (identificacion),
                         CONSTRAINT UKsk2ttlpp6eid09hulymqx6cc5 UNIQUE (cliente_id)
);

-- Insertar datos iniciales en persona
INSERT INTO persona (dtype, nombre, genero, edad, identificacion, direccion, telefono, cliente_id, contrasena, estado)
VALUES ('Cliente', 'Jose Lema', 'M', 30, '123456789', 'Otavalo sn y principal', '098254785', 'C001', '1234', true);

-- Crear la base de datos cuenta_db
CREATE DATABASE cuenta_db;
\c cuenta_db

-- Crear la tabla cuenta
CREATE TABLE cuenta (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        cliente_id VARCHAR(255) NOT NULL,
                        estado BOOLEAN NOT NULL,
                        numero_cuenta VARCHAR(255) NOT NULL,
                        saldo_inicial DOUBLE PRECISION NOT NULL,
                        tipo_cuenta VARCHAR(255) NOT NULL,
                        CONSTRAINT UKpj7ncg765kt4klndu25bwbwe4 UNIQUE (numero_cuenta)
);

-- Crear la tabla movimiento
CREATE TABLE movimiento (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            fecha TIMESTAMP NOT NULL,
                            saldo DOUBLE PRECISION NOT NULL,
                            tipo_movimiento VARCHAR(255) NOT NULL,
                            valor DOUBLE PRECISION NOT NULL,
                            cuenta_id BIGINT NOT NULL,
                            CONSTRAINT FK4ea11fe7p3xa1kwwmdgi9f2fi FOREIGN KEY (cuenta_id) REFERENCES cuenta(id)
);

-- Insertar datos iniciales en cuenta
INSERT INTO cuenta (cliente_id, estado, numero_cuenta, saldo_inicial, tipo_cuenta)
VALUES ('C001', true, '478758', 2000.0, 'Ahorros');

-- Insertar datos iniciales en movimiento
INSERT INTO movimiento (fecha, saldo, tipo_movimiento, valor, cuenta_id)
VALUES ('2022-02-10 10:00:00', 1425.0, 'Retiro', -575.0, 1);